source("R/app-load.R", local = TRUE)
source("R/app-function.R", local = TRUE)
source("R/app-theme.R", local = TRUE)
source("R/mod-cleaning.R", local = TRUE)
source("R/data-quiz.R", local = TRUE)
source("R/mod-quiz.R", local = TRUE)
source("R/data-stats.R", local = TRUE)
source("R/ui-stats.R", local = TRUE)
source("R/ui-ai-training.R", local = TRUE)
source("R/ui-ai-pages.R", local = TRUE)
source("R/app-ui.R", local = TRUE)
source("R/app-server.R", local = TRUE)

shinyApp(ui, server)
